source ~/.vim/plugins.vim
source ~/.vim/options.vim
source ~/.vim/keybinds.vim
source ~/.vim/colours.vim
source ~/.vim/fzf.vim
source ~/.vim/coc.vim
source ~/.vim/vim-highlightedyank.vim


" " Force yats syntax for TypeScript & TSX files
autocmd FileType typescript,typescriptreact runtime! syntax/yats.vim
