source ~/.vim/plugins.vim
source ~/.vim/options.vim
source ~/.vim/keybinds.vim
source ~/.vim/colours.vim
source ~/.vim/fzf.vim
source ~/.vim/coc.vim
source ~/.vim/vim-highlightedyank.vim


" " Force yats syntax for TypeScript & TSX files
autocmd FileType typescript,typescriptreact runtime! syntax/yats.vim

augroup CocSigns
  autocmd!
  autocmd User CocNvimInit call s:define_coc_signs()
augroup END

function! s:define_coc_signs() abort
  sign define CocError   text=✘ texthl=CocErrorSign
  sign define CocWarning text=󰚌 texthl=CocWarningSign
  sign define CocInfo    text=◉ texthl=CocInfoSign
  sign define CocHint    text= texthl=CocHintSign
endfunction


highlight CocGitSignAdded   ctermbg=NONE ctermfg=Green
highlight CocGitSignChanged ctermbg=NONE ctermfg=Cyan
highlight CocGitSignRemoved  ctermbg=NONE ctermfg=Red


let g:netrw_keepdir = 0

augroup custom_nginx
  autocmd!
  autocmd FileType nginx setlocal iskeyword+=$
  autocmd FileType nginx let b:coc_additional_keywords = ['$']
augroup end

autocmd FileType nginx setlocal omnifunc=coc#complete

let g:coc_python_path = '/home/devdad/.pyenv/versions/3.12.3/bin/python'
let $PATH = expand("~/.pyenv/shims:~/.pyenv/bin:") . $PATH
