#!/bin/bash
dir="$(cd "$(dirname "$0")" && pwd)"
local_cfg="$dir/config.local"

# Defaults
BAR_FONT=10
BAR_BG=#1c1f20
BAR_FG=#ebdbb2
WIN_FOCUSED=#d79921
WIN_INACTIVE=#504945
WIN_UNFOCUSED=#3c3836
WIN_URGENT=#cc241d
WIN_DIM=#a89984
PICOM_FADING=false
WALLPAPER=$HOME/.config/dotfiles/i3/gruv-rocket.png

if [ -f "$local_cfg" ]; then
    source "$local_cfg"
fi

sed -e "s|@@BAR_FONT@@|$BAR_FONT|g" \
    -e "s|@@BAR_BG@@|$BAR_BG|g" \
    -e "s|@@BAR_FG@@|$BAR_FG|g" \
    -e "s|@@WIN_FOCUSED@@|$WIN_FOCUSED|g" \
    -e "s|@@WIN_INACTIVE@@|$WIN_INACTIVE|g" \
    -e "s|@@WIN_UNFOCUSED@@|$WIN_UNFOCUSED|g" \
    -e "s|@@WIN_URGENT@@|$WIN_URGENT|g" \
    -e "s|@@WIN_DIM@@|$WIN_DIM|g" \
    -e "s|@@WALLPAPER@@|$WALLPAPER|g" \
    "$dir/config.base" > "$dir/config"

# Generate i3status-rust config
sed -e "s|@@BAR_BG@@|$BAR_BG|g" \
    -e "s|@@BAR_FG@@|$BAR_FG|g" \
    -e "s|@@COLOR_GOOD@@|${COLOR_GOOD:-$BAR_FG}|g" \
    -e "s|@@COLOR_WARNING@@|${COLOR_WARNING:-#d79921}|g" \
    -e "s|@@COLOR_CRITICAL@@|${COLOR_CRITICAL:-#cc241d}|g" \
    "$dir/../i3status-rust/config.base.toml" > "$dir/../i3status-rust/config.toml"

# Generate rofi config
sed -e "s|@@BAR_BG@@|$BAR_BG|g" \
    -e "s|@@BAR_FG@@|$BAR_FG|g" \
    -e "s|@@WIN_FOCUSED@@|$WIN_FOCUSED|g" \
    -e "s|@@WIN_UNFOCUSED@@|$WIN_UNFOCUSED|g" \
    -e "s|@@WIN_DIM@@|$WIN_DIM|g" \
    -e "s|@@WIN_URGENT@@|$WIN_URGENT|g" \
    "$dir/../rofi/config.base.rasi" > "$dir/../rofi/config.rasi" 2>/dev/null

# Copy rofi config to ~/.config/rofi (use temp file to avoid hardlink collision)
cp "$dir/../rofi/config.rasi" "$HOME/.config/rofi/config.rasi" 2>/dev/null || true

# Generate picom config from template
sed -e "s|@@PICOM_FADING@@|${PICOM_FADING:-false}|g" \
    "$dir/../picom/picom.base.conf" > "$dir/../picom/picom.conf"
mkdir -p "$HOME/.config/picom"
cp "$dir/../picom/picom.conf" "$HOME/.config/picom/picom.conf"

# Generate kitty current-theme.conf
kitty_theme_src="$dir/../kitty/themes/${KITTY_THEME}.conf"
if [ -f "$kitty_theme_src" ]; then
  cp "$kitty_theme_src" "$dir/../kitty/current-theme.conf"
  mkdir -p "$HOME/.config/kitty"
  cp "$kitty_theme_src" "$HOME/.config/kitty/current-theme.conf"
  pkill -x kitty --signal SIGUSR1 2>/dev/null
fi

# Generate Emacs theme file
emacs_theme_dir="$dir/../emacs"
mkdir -p "$emacs_theme_dir"
emacs_theme_file="$emacs_theme_dir/theme.el"
{
  echo ";; Auto-generated by generate.sh - do not edit"
  if [ -n "$CATPPUCCIN_FLAVOR" ]; then
    echo "(setq catppuccin-flavor '$CATPPUCCIN_FLAVOR)"
  fi
  echo "(load-theme '${EMACS_THEME:-nezburn} t)"
} > "$emacs_theme_file"
