#!/bin/bash
dir="$(cd "$(dirname "$0")" && pwd)"
local_cfg="$dir/config.local"

# Defaults
BAR_FONT=8
BAR_BG=#1c1f20
BAR_FG=#ebdbb2
WIN_FOCUSED=#d79921
WIN_INACTIVE=#504945
WIN_UNFOCUSED=#3c3836
WIN_URGENT=#cc241d
WIN_DIM=#a89984
PICOM_FADING=false
NET_DEVICE=auto
EDITOR_CMD="emacs"
WALLPAPER=$HOME/.config/dotfiles/i3/gruv-rocket.png

if [ -f "$local_cfg" ]; then
    source "$local_cfg"
fi

# Network interface: leave NET_DEVICE=auto (default) to let i3status-rust
# follow the default-route interface itself — works for wifi AND ethernet and
# updates live. Pin a specific one in config.local (e.g. NET_DEVICE=eth0) to override.
if [ "$NET_DEVICE" = "auto" ] || [ -z "$NET_DEVICE" ]; then
    NET_DEVICE_LINE=""
else
    NET_DEVICE_LINE="device = \"$NET_DEVICE\""
fi

BAR_FONT=${BAR_FONT:-10}
sed -e "s|@@BAR_FONT@@|$BAR_FONT|g" \
    -e "s|@@BAR_BG@@|$BAR_BG|g" \
    -e "s|@@BAR_FG@@|$BAR_FG|g" \
    -e "s|@@WIN_FOCUSED@@|$WIN_FOCUSED|g" \
    -e "s|@@WIN_INACTIVE@@|$WIN_INACTIVE|g" \
    -e "s|@@WIN_UNFOCUSED@@|$WIN_UNFOCUSED|g" \
    -e "s|@@WIN_URGENT@@|$WIN_URGENT|g" \
    -e "s|@@WIN_DIM@@|$WIN_DIM|g" \
    -e "s|@@WALLPAPER@@|$WALLPAPER|g" \
    -e "s|@@EDITOR_CMD@@|$EDITOR_CMD|g" \
    "$dir/config.base" > "$dir/config"

# Generate i3status-rust config
sed -e "s|@@BAR_BG@@|$BAR_BG|g" \
    -e "s|@@BAR_FG@@|$BAR_FG|g" \
    -e "s|@@COLOR_GOOD@@|${COLOR_GOOD:-$BAR_FG}|g" \
    -e "s|@@COLOR_WARNING@@|${COLOR_WARNING:-#d79921}|g" \
    -e "s|@@COLOR_CRITICAL@@|${COLOR_CRITICAL:-#cc241d}|g" \
    -e "s|@@WIN_FOCUSED@@|${WIN_FOCUSED:-#d79921}|g" \
    -e "s|@@WIN_INACTIVE@@|${WIN_INACTIVE:-#504945}|g" \
    -e "s|@@NET_DEVICE_LINE@@|$NET_DEVICE_LINE|g" \
    "$dir/../i3status-rust/config.base.toml" > "$dir/../i3status-rust/config.toml"

# Generate rofi config
sed -e "s|@@BAR_BG@@|$BAR_BG|g" \
    -e "s|@@BAR_FG@@|$BAR_FG|g" \
    -e "s|@@WIN_FOCUSED@@|$WIN_FOCUSED|g" \
    -e "s|@@WIN_UNFOCUSED@@|$WIN_UNFOCUSED|g" \
    -e "s|@@WIN_DIM@@|$WIN_DIM|g" \
    -e "s|@@WIN_URGENT@@|$WIN_URGENT|g" \
    "$dir/../rofi/config.base.rasi" > "$dir/../rofi/config.rasi" 2>/dev/null

# Copy rofi config to ~/.config/rofi (use temp file to avoid hardlink collision)
cp "$dir/../rofi/config.rasi" "$HOME/.config/rofi/config.rasi" 2>/dev/null || true

# Generate picom config from template
sed -e "s|@@PICOM_FADING@@|${PICOM_FADING:-false}|g" \
    "$dir/../picom/picom.base.conf" > "$dir/../picom/picom.conf"
mkdir -p "$HOME/.config/picom"
rm -f "$HOME/.config/picom/picom.conf"
cp "$dir/../picom/picom.conf" "$HOME/.config/picom/picom.conf"

# Generate kitty current-theme.conf
kitty_theme_src="$dir/../kitty/themes/${KITTY_THEME}.conf"
if [ -f "$kitty_theme_src" ]; then
  cp "$kitty_theme_src" "$dir/../kitty/current-theme.conf"
  mkdir -p "$HOME/.config/kitty"
  cp "$kitty_theme_src" "$HOME/.config/kitty/current-theme.conf"
  pkill -x kitty --signal SIGUSR1 2>/dev/null
fi

# Generate Emacs theme file
emacs_theme_dir="$dir/../emacs"
mkdir -p "$emacs_theme_dir"
emacs_theme_file="$emacs_theme_dir/theme.el"
{
  echo ";; Auto-generated by generate.sh - do not edit"
  if [ -n "$CATPPUCCIN_FLAVOR" ]; then
    echo "(setq catppuccin-flavor '$CATPPUCCIN_FLAVOR)"
  fi
  echo "(load-theme '${EMACS_THEME:-nezburn} t)"
} > "$emacs_theme_file"

# Deploy textfox to Firefox profile
deploy_textfox() {
  local profile_dir="$1"
  local chrome_dir="$profile_dir/chrome"

  # Backup existing chrome if it's not textfox
  if [ -f "$chrome_dir/userChrome.css" ] && ! grep -q "textfox" "$chrome_dir/userChrome.css" 2>/dev/null; then
    local bak="$profile_dir/chrome.bak"
    [ ! -d "$bak" ] && cp -r "$chrome_dir" "$bak"
  fi

  # Copy textfox chrome files
  mkdir -p "$chrome_dir"
  cp -r "$dir/../zen/textfox/"* "$chrome_dir/"

  # Generate config.css with theme colors
  sed -e "s|@@BG@@|$BAR_BG|g" \
      -e "s|@@FG@@|$BAR_FG|g" \
      -e "s|@@ACCENT@@|$WIN_FOCUSED|g" \
      -e "s|@@BORDER@@|$WIN_INACTIVE|g" \
      "$dir/../zen/config.css.base" > "$chrome_dir/config.css"
}

# Generate Zen browser userChrome.css
generate_zen_userchrome() {
  local config_dir="$HOME/.config/zen"
  local ini="$config_dir/profiles.ini"
  local active_profile=$(grep -A1 '^\[Install' "$ini" 2>/dev/null | grep "^Default=" | head -1 | cut -d= -f2)
  [ -z "$active_profile" ] && active_profile=$(grep -B1 "^Default=1" "$ini" 2>/dev/null | grep "^Path=" | head -1 | cut -d= -f2)
  [ -z "$active_profile" ] && return

  local chrome_dst="$config_dir/$active_profile/chrome/userChrome.css"
  mkdir -p "$(dirname "$chrome_dst")"
  sed -e "s|@@BAR_BG@@|$BAR_BG|g" \
      -e "s|@@BAR_FG@@|$BAR_FG|g" \
      -e "s|@@WIN_FOCUSED@@|$WIN_FOCUSED|g" \
      -e "s|@@WIN_INACTIVE@@|$WIN_INACTIVE|g" \
      -e "s|@@WIN_UNFOCUSED@@|$WIN_UNFOCUSED|g" \
      -e "s|@@WIN_DIM@@|$WIN_DIM|g" \
      "$dir/../zen/userChrome.css.base" > "$chrome_dst"
}

# Enable browser prefs for custom CSS
set_browser_prefs() {
  local config_dir="$1"
  local ini="$config_dir/profiles.ini"
  local active_profile=$(grep -A1 '^\[Install' "$ini" 2>/dev/null | grep "^Default=" | head -1 | cut -d= -f2)
  [ -z "$active_profile" ] && active_profile=$(grep -B1 "^Default=1" "$ini" 2>/dev/null | grep "^Path=" | head -1 | cut -d= -f2)
  [ -z "$active_profile" ] && return

  local userjs="$config_dir/$active_profile/user.js"
  for pref in 'toolkit.legacyUserProfileCustomizations.stylesheets' 'devtools.debugger.remote-enabled' 'devtools.chrome.enabled'; do
    if ! grep -q "$pref" "$userjs" 2>/dev/null; then
      echo "user_pref(\"$pref\", true);" >> "$userjs"
    fi
  done
}

# Firefox — deploy textfox
firefox_profiles="$HOME/.config/mozilla/firefox/profiles.ini"
firefox_active=$(grep -A1 '^\[Install' "$firefox_profiles" 2>/dev/null | grep "^Default=" | head -1 | cut -d= -f2)
[ -z "$firefox_active" ] && firefox_active=$(grep -B1 "^Default=1" "$firefox_profiles" 2>/dev/null | grep "^Path=" | head -1 | cut -d= -f2)
if [ -n "$firefox_active" ]; then
  deploy_textfox "$HOME/.config/mozilla/firefox/$firefox_active"
  set_browser_prefs "$HOME/.config/mozilla/firefox"
fi

# Zen — simple userChrome.css
generate_zen_userchrome
set_browser_prefs "$HOME/.config/zen"
