[theme]
theme = "plain"

[theme.overrides]
bg = "@@BAR_BG@@"
fg = "@@BAR_FG@@"
separator = ""
separator_bg = "@@BAR_BG@@"
separator_fg = "@@BAR_FG@@"

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
format = " $item <span color='@@WIN_FOCUSED@@'>$utilization</span> "

[[block]]
block = "memory"
format = " $item <span color='@@WIN_INACTIVE@@'>$mem_used_percents</span> "

[[block]]
block = "disk_space"
format = " $item <span color='@@WIN_UNFOCUSED@@'>$available</span> "

[[block]]
block = "net"
format = " $item <span color='@@WIN_URGENT@@'>$ssid $signal_strength</span> "
format_alt = " $item <span color='@@WIN_URGENT@@'>$ip</span> "

[[block]]
block = "sound"
format = " $item <span color='@@WIN_DIM@@'>$volume</span> "

[[block]]
block = "custom"
command = "printf '   %s%%' $(cat /sys/class/power_supply/BAT1/capacity 2>/dev/null || echo '?')"
interval = 30

[[block]]
block = "custom"
command = "~/.config/i3/powerprofile.sh"
interval = 5

[[block]]
block = "time"
format = "  $item  <span color='@@BAR_FG@@'>$timestamp.datetime(f:'%a %d/%m %H:%M')</span> "