# Ember
background #1a0f08
foreground #eeddc0
selection_background #4a382c
selection_foreground #eeddc0
url_color #8ba3ad
cursor #ff9e2e
cursor_text_color #1a0f08
active_border_color #ff9e2e
inactive_border_color #3a2b21
bell_border_color #9db06a
tab_bar_style powerline
active_tab_foreground #eeddc0
active_tab_background #2a1c12
inactive_tab_foreground #96755f
inactive_tab_background #120a05

# black
color0 #1a0f08
color8 #3a2b21

# red
color1 #ff3b1f
color9 #ff5c3a

# green
color2 #9db06a
color10 #9db06a

# yellow
color3 #fdbd28
color11 #fdbd28

# blue
color4 #8ba3ad
color12 #8ba3ad

# magenta
color5 #cf7f62
color13 #cf7f62

# cyan
color6 #cfa878
color14 #cfa878

# white
color7 #eeddc0
color15 #f5e8cf
