# Gilded Noir
background #0B0B0C
foreground #C3B285
selection_background #866C2C
selection_foreground #0B0B0C
url_color #D4AF37
cursor #D4AF37
cursor_text_color #0B0B0C
active_border_color #D4AF37
inactive_border_color #202027
bell_border_color #866C2C
tab_bar_style separator
active_tab_foreground #0B0B0C
active_tab_background #D4AF37
inactive_tab_foreground #6A6249
inactive_tab_background #131316

# black
color0 #131316
color8 #5A5443

# red
color1 #6A6249
color9 #866C2C

# green
color2 #866C2C
color10 #A88C46

# yellow
color3 #A88C46
color11 #C3B285

# blue
color4 #6A6249
color12 #866C2C

# magenta
color5 #866C2C
color13 #A88C46

# cyan
color6 #A88C46
color14 #C3B285

# white
color7 #C3B285
color15 #D4AF37
