-- return {
--   {
--     "rockyzhang24/arctic.nvim",
--     dependencies = { "rktjmp/lush.nvim" },
--     name = "arctic",
--     branch = "main",
--     priority = 1000,
--     config = function()
--       vim.cmd("colorscheme arctic")
--     end,
--   },
-- }
return {}
-- return {
--   {
--     "AstroNvim/astrotheme",
--     priority = 1000,
--     config = function()
--       require("astrotheme").setup({
--         -- style = "dark",
--         style = {
--           float = true, -- enable floating window background
--           border = true, -- enable floating window border
--         },
--         palettes = {
--           astrodark = {
--             ui = { accent = "#B3B3B3" }, -- lighter accent
--           },
--         },
--         highlights = {
--           astrodark = {
--             FloatBorder = { fg = "#B3B3B3", bg = "none" }, -- pastel border
--             NormalFloat = { bg = "#1a1b26" }, -- lighter float bg
--           },
--         },
--       })
--       vim.cmd("colorscheme astrodark")
--     end,
--   },
-- }
