return {}

-- return {
--   {
--     "Automattic/harper",
--     ft = { "javascript", "javascriptreact", "typescript", "typescriptreact", "markdown", "gitcommit" },
--     config = function()
--       require("lspconfig").harper_ls.setup({
--         filetypes = {
--           "javascript",
--           "javascriptreact",
--           "typescript",
--           "typescriptreact",
--           "markdown",
--           "gitcommit",
--         },
--         settings = {
--           ["harper-ls"] = {
--             linters = {
--               spell_check = true,
--               sentence_capitalization = true,
--               repeated_words = true,
--               avoid_curses = true,
--               passive_voice = true,
--               weasel_words = true,
--               custom_word_list = {
--                 deny = {
--                   "creater",
--                   -- add more personal "anti-patterns" here
--                 },
--               },
--             },
--           },
--         },
--       })
--     end,
--   },
-- }
